[run]
nsubruns = 1
files_per_subrun = 1
require_success = true

[workflow]
sbnnusyst_env = "/lus/flare/projects/neutrinoGPU/larsoft_hpc/envs/sbnnusyst.env"
sbnnusyst_fcl = "Ar23+_knobs.ParamHeader.fcl"
stage0_path = [
	"/lus/flare/projects/neutrinoGPU/icarus/mc/run2/production_mc_2025A_ICARUS_Overlays_BNB_RUN2_September_v10_06_00_04p04_stage0/",
	"/lus/flare/projects/neutrinoGPU/icarus/mc/run2/production_mc_2025A_ICARUS_Overlays_BNB_MC_RUN2_September_v10_06_00_04p04_stage0/"
]

[app.larsoft]
software = "icaruscode"
version = "v10_06_00_14"
qual = "e26:prof"
nevts = -1
experiment = "icarus"
lar_args = ""
env_file = "/lus/flare/projects/neutrinoGPU/larsoft_hpc/envs/icaruscode-v10_06_00_14.env"
overlays = [
	"/lus/flare/projects/neutrinoGPU/larsoft_hpc/images/larsoft-v10_06_00.squashfs",
	"/lus/flare/projects/neutrinoGPU/larsoft_hpc/images/icarus-v10_06_00_14_delta.squashfs"
]

[app.larsoft.tarballs]
icaruscode = "/lus/flare/projects/neutrinoGPU/scisoft/tarballs/icaruscode-10.06.00.14-slf7-x86_64-e26-prof.tar.bz2"
icarus_data = "/lus/flare/projects/neutrinoGPU/scisoft/tarballs/icarus_data-10.06.06-noarch.tar.bz2"

[job]
queue = "debug"
walltime = "1:00:00"
nodes_per_block = 1
max_workers_per_node = 102
allocation = "neutrinoGPU::ICARUSRun4_Summer2025_MC"
retries = 0
initialize_logging = false

[workflow.fcls]
stage1 = "stage1_run2_larcv_icarus_overlay_wiremodcorr.fcl"
caf = "cafmakerjob_icarus_detsim2d_systtools_and_fluxwgt_overlay.fcl"

[app.larsoft.metadata]
mdprojectversion = "v10_06_00_14"
