[run]
nsubruns = 1
files_per_subrun = 1
require_success = true

[workflow]
sbnnusyst_env = "/lus/flare/projects/neutrinoGPU/larsoft_hpc/envs/sbnnusyst.env"
sbnnusyst_fcl = "Ar23+_knobs.ParamHeader.fcl"
stage1_path = "/lus/flare/projects/neutrinoGPU/twester/icarus_recaf_prod/stage1"
skip_file_list = "/lus/flare/projects/neutrinoGPU/twester/icarus_recaf_sce_prod/sce_skip_list.txt"

[app.larsoft]
software = "icaruscode"
version = "v10_06_00_12"
qual = "e26:prof"
nevts = -1
experiment = "icarus"
lar_args = ""
env_file = "/lus/flare/projects/neutrinoGPU/larsoft_hpc/envs/icaruscode-v10_06_00_12.env"
overlays = [
	"/lus/flare/projects/neutrinoGPU/larsoft_hpc/images/larsoft-v10_06_00.squashfs",
	"/lus/flare/projects/neutrinoGPU/larsoft_hpc/images/icarus-v10_06_00_12_delta.squashfs"
]

[app.larsoft.tarballs]
icaruscode = "/lus/flare/projects/neutrinoGPU/scisoft/tarballs/icaruscode-10.06.00.12-slf7-x86_64-e26-prof.tar.bz2"
icarus_data = "/lus/flare/projects/neutrinoGPU/scisoft/tarballs/icarus_data-10.06.06-noarch.tar.bz2"

[job]
queue = "debug"
walltime = "1:00:00"
nodes_per_block = 1
max_workers_per_node = 102
allocation = "neutrinoGPU::ICARUSRun4_Summer2025_MC"
retries = 0
initialize_logging = false

[workflow.fcls]
caf = "cafmakerjob_icarus_sce_detsim2d_overlay.fcl"

[app.larsoft.metadata]
mdprojectversion = "v10_06_00_12"
