[site]
name = "aurora"
cpus_per_node = 102
cores_per_worker = 1
scheduler_options = "#PBS -l filesystems=home:flare"
launcher_options = "--ppn 1 --depth=104 --cpu-bind depth"
cpu_affinity = "aurora"
available_accelerators = 102
pbs_filesystems = "home:flare"
max_futures = 100000
worker_init = [
    "export TMPDIR=/tmp/",
]
monitor_cmd = "/home/twester/sbn_parsl_v01/tools/lar_mon.sh --interval 30 -o 'node_mon_$(hostname).jsonl'"

[app.larsoft]
container_path = "/lus/flare/projects/neutrinoGPU/containers/slf7.sif"
larsoft_top = "/lus/flare/projects/neutrinoGPU/scisoft/larsoft"
simulation_inputs = "/lus/flare/projects/neutrinoGPU/simulation_inputs_striped"

[app.larsoft.metadata]
exe = "/lus/flare/projects/neutrinoGPU/larsoft_hpc/tools/sbnpoms_metadata_injector_data.sh"

[site.queues.debug]
nodes_min = 1
nodes_max = 2
walltime_min = "00:05:00"
walltime_max = "01:00:00"

[site.queues.debug-scaling]
nodes_min = 2
nodes_max = 256
walltime_min = "00:05:00"
walltime_max = "01:00:00"

[site.queues.prod]
is_routing = true
routes_to = ["small", "medium", "large"]

[site.queues.small]
nodes_min = 256
nodes_max = 1024
walltime_min = "00:05:00"
walltime_max = "12:00:00"

[site.queues.medium]
nodes_min = 1025
nodes_max = 1919
walltime_min = "00:05:00"
walltime_max = "18:00:00"

[site.queues.large]
nodes_min = 1920
nodes_max = 10624
walltime_min = "00:05:00"
walltime_max = "24:00:00"
