[site]
name = "aurora"
cpus_per_node = 104
cores_per_worker = 1
scheduler_options = "#PBS -l filesystems=home:flare"
launcher_options = "-n 1 --ppn 1 --depth=104 --cpu-bind depth"
cpu_affinity = "none"
available_accelerators = 102
pbs_filesystems = "home:flare"
worker_venv_name = "sbn"
worker_init = [
    "export TMPDIR=/tmp/",
    "module load frameworks",
    "source ~/.venv/sbn/bin/activate"
]

[larsoft]
container_path = "/lus/flare/projects/neutrinoGPU/containers/slf7.sif"
larsoft_top = "/lus/flare/projects/neutrinoGPU/scisoft/larsoft"
simulation_inputs = "/lus/flare/projects/neutrinoGPU/simulation_inputs_striped"

[larsoft.metadata]
exe = "/lus/flare/projects/neutrinoGPU/scisoft/larsoft/sbndutil/v10_06_01/bin/sbndpoms_metadata_injector.sh"

[app.spine]
model_path = "/lus/flare/projects/neutrinoGPU/models/spine/model.pt"
batch_size = 32
device = "cuda"
