name = "local"
cpus_per_node = 32
cores_per_worker = 1
container_path = ""
larsoft_top = ""
scheduler_options = ""
launcher_options = ""
cpu_affinity = "none"
available_accelerators = 0
pbs_filesystems = ""
worker_venv_name = "sbn"
simulation_inputs = ""
