[site]
name = "polaris"
cpus_per_node = 32
cores_per_worker = 1
scheduler_options = "#PBS -l filesystems=home:grand:eagle\n#PBS -l place=scatter"
launcher_options = "--depth=64 --ppn 1"
cpu_affinity = "alternating"
available_accelerators = 32
pbs_filesystems = "home:grand:eagle"
worker_venv_name = "sbn"
worker_init = [
    "export TMPDIR=/tmp/",
    "source ~/.venv/sbn/bin/activate"
]

[larsoft]
container_path = "/lus/grand/projects/neutrinoGPU/software/containers/slf7.sif"
larsoft_top = "/lus/grand/projects/neutrinoGPU/software/larsoft"
simulation_inputs = "/lus/grand/projects/neutrinoGPU/simulation_inputs"

[larsoft.metadata]
exe = "/lus/flare/projects/neutrinoGPU/scisoft/larsoft/sbndutil/v10_06_01/bin/sbndpoms_metadata_injector.sh"

[app.spine]
model_path = "/lus/flare/projects/neutrinoGPU/models/spine/model.pt"
batch_size = 32
device = "cuda"
