[run]
nsubruns = 1

[workflow]
subruns_per_caf = 20
full_keep_fraction = 0.05

[app.larsoft]
software = "sbndcode"
version = "v10_06_00_04"
qual = "e26:prof"
nevts = 20
experiment = "sbnd"
lar_args = ""

[job]
queue = "debug"
walltime = "1:00:00"
nodes_per_block = 1
allocation = "neutrinoGPU::debug2"
retries = 0

[workflow.fcls]
gen = "prodgenie_corsika_proton_rockbox_sbnd.fcl"
g4 = "standard_g4_rockbox_sbnd.fcl"
detsim = "standard_detsim_sbnd.fcl"
reco1 = "standard_reco1_sbnd.fcl"
reco2 = "standard_reco2_sbnd.fcl"
caf = "cafmakerjob_sbnd_sce_systtools_and_fluxwgt.fcl"

[app.larsoft.metadata]
mdprojectversion = "v10_06_00_04"
