[run]
nsubruns = 1
files_per_subrun = 1

[workflow]

[larsoft]
software = "sbndcode"
version = "v10_06_00_04"
qual = "e26:prof"
nevts = 20
experiment = "sbnd"
lar_args = ""

[job]
queue = "debug"
walltime = "1:00:00"
nodes_per_block = 1
allocation = "neutrinoGPU::debug2"
retries = 0

[workflow.fcls]
decode = "run_decoders_job.fcl"
pot = "run_sbndbnbinfo_sbn.fcl"
reco1 = "reco1_data_dnnroi.fcl"
reco2 = "reco2_data.fcl"
caf = "cafmakerjob_sbnd_data_sce_bnblight_dnnroi.fcl"

[larsoft.metadata]
mdprojectversion = "v10_06_00_04"
