[run]
nsubruns = 32
files_per_subrun = 1

[workflow]

[larsoft]
software = "sbndcode"
version = "v10_10_03_02"
qual = "e26:prof"
nevts = 10
experiment = "sbnd"
lar_args = ""

[job]
queue = "debug"
walltime = "1:00:00"
nodes_per_block = 1
allocation = "14453"
retries = 0

[fcls]
decode = "run_decoders_job.fcl"
pot = "run_sbndbnbinfo_sbn.fcl"
reco1 = "reco1_data_dnnroi.fcl"
reco2 = "reco2_data.fcl"
caf = "cafmakerjob_sbnd_data_sce_bnblight_dnnroi.fcl"

[larsoft.metadata]
mdprojectversion = "v10_10_03_02"
